version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    entrypoint: "npm run dev"
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - "8080:80"
  redis:
    image: "redis:alpine"