openapi: 3.0.0
info:
  version: 1.0.0
  title: manabi Swagger
  description: manabi Swagger Specification
servers:
  - url: "http://localhost:{port}/"
    variables:
      port:
        default: "4010"
        enum:
          - "4010"
          - "8080"

paths:
  /me:
    $ref: ./path/me.yaml
